# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7aa0b8163a7e6c16df55fc2278534c3cf06fabe7e0f1fe9bd4775a8023ac66e1377979a3876583fd535b6ddf323481ebf41f05b9d41efb8604952b17fdcc55

test:
  secret_key_base: 49e0488ca35402a7cc1f9f4be2c2441379f38e8275489b8cddb60620d682f4b4d4e4336b7721aa51683dfcecbdef87d17811138b00dfdba4b604afd5ee440230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: c5958e20ddd7b0e5e4e36842986ef2fb7024226771da8ce9511296d2b2183d5dd719e50bfbd1ba3e7a87e7416c385cbad26b94f43dd870063d2dab053e760428
